routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Login
Route::group(['prefix' => 'admin', 'namespace' => 'admin'], function() {
    Route::get('login','AdminController@getLogin')->name('get-admin-Login');
    Route::post('login','AdminController@postLogin')->name('post-admin-Login');
    Route::get('logout','AdminController@getLogout')->name('get-admin-Logout');
});

Route::group(['middleware'=>'CheckAdminLogin', 'namespace' => 'admin'], function() {
    Route::get('/admin','AdminController@index');
    Route::get('/admin/dashboard','AdminController@show_dashboard');
});

// Website
//Route::get('/pages','HomeController@index');
Route::get('/pages/home','HomeController@Home')->name('pages.home');
Route::get('/pages/about','HomeController@About')->name('pages.about');
Route::get('/pages/shop','HomeController@Shop_All')->name('pages.shop');
Route::get('/pages/contact','HomeController@Contact')->name('pages.contact');
Route::get('/pages/single','HomeController@Single')->name('pages.single');
Route::get('/pages/checkout','HomeController@Checkout')->name('pages.checkout');
Route::get('/pages/404','HomeController@Err')->name('pages.404');
Route::get('/pages/shop_cate/{id}','HomeController@search_Category')->name('pages.search_category');
Route::get('/pages/shop_brand/{id}','HomeController@search_Brand')->name('pages.search_brand');
Route::get('/pages/single/{id}','HomeController@detail_Pro')->name('pages.detail_pro');


// Admin
Route::group(['middleware'=>'CheckAdminLogin','prefix'=>'admin/user','namespace' => 'admin'],function(){
    Route::get('/', 'UserController@index')->name('user.index');
    Route::get('/index','UserController@index')->name('user.index');
    Route::get('/create','UserController@getcreate')->name('user.create');
    Route::post('/create','UserController@postcreate')->name('user.postcreate');
    Route::get('edit/{id}','UserController@getedit')->name('user.getedit');
	Route::post('edit/{id}','UserController@postedit')->name('user.postedit');
    Route::get('delete/{id}','UserController@delete')->name('user.delete');
    Route::get('active/{id}','UserController@active')->name('user.active');
    Route::get('unactive/{id}','UserController@unactive')->name('user.unactive');
});

// Category
Route::resource('admin/category',admin\CategoryController::class);
Route::get('admin/category/delete/{id}', 'admin\CategoryController@delete')->name('category.delete');
Route::get('admin/category/prodictlist/{id}', 'admin\CategoryController@productlist')->name('category.productlist');
Route::get('admin/category/active/{id}', 'admin\CategoryController@active')->name('category.active');
Route::get('admin/category/unactive/{id}', 'admin\CategoryController@unactive')->name('category.unactive');

// Brand
Route::resource('admin/brand',admin\BrandController::class);
Route::get('admin/brand/delete/{id}', 'admin\BrandController@delete')->name('brand.delete');
Route::get('admin/brand/prodictlist/{id}', 'admin\BrandController@productlist')->name('brand.productlist');
Route::get('admin/brand/active/{id}', 'admin\BrandController@active')->name('brand.active');
Route::get('admin/brand/unactive/{id}', 'admin\BrandController@unactive')->name('brand.unactive');

// Product
Route::resource('admin/product',admin\ProductController::class);
Route::get('admin/product/delete/{id}', 'admin\ProductController@delete')->name('product.delete');
Route::get('admin/product/active/{id}', 'admin\ProductController@active')->name('product.active');
Route::get('admin/product/unactive/{id}', 'admin\ProductController@unactive')->name('product.unactive');

resources/views/admin/QLBrand/create.blade.php
@extends('layout_admin')
@section('admin_content')
  <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title" style="text-align:center">Thêm Thương Hiệu Sản Phẩm</h4>
                                <h6 class="card-subtitle" style="text-align: center;">Thêm Thương Hiệu<code>.table</code></h6>
                                <div class="table-responsive">
                                <form action="{{route('brand.store')}}" method="POST" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    <table class="table user-table">
                                        <tbody>
                                            <tr>
                                                <label for="image">Hình Ảnh:</label>
                                                <input type="file" class="form-control" id="image" name="image" style="padding-top: 3px">
                                            </tr>
                                            <tr>
                                                <label for="name">Tên Thương Hiệu:</label>
                                            <input type="text" class="form-control" id="name" name="name" value="" required>
                                            </tr>
                                            <tr>
                                                <label for="content">Mô Tả:</label>
                                                <textarea type="text" class="form-control" id='id_ckeditor' name="content" value="" required></textarea>
                                            </tr>
                                            <tr>
                                                <label for="status">Trạng Thái:</label>
                                                <select type="text" class="form-control" id="status" name="status">
                                                    <option value="1">Nhập Hàng</option>
                                                    <option value="0">Ngưng Nhập Hàng</option>
                                                </select>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <button type="submit" name="btnregister"class="btn btn-primary" style="background:#26c6da">Thực Hiện</button>
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endsection

resources/views/admin/QLBrand/edit.blade.php
@extends('layout_admin')
@section('admin_content')
  <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title" style="text-align:center">Chỉnh Sửa Thương Hiệu Sản Phẩm</h4>
                                <h6 class="card-subtitle" style="text-align: center;">Chỉnh Sửa Thương Hiệu<code>.table</code></h6>
                                <div class="table-responsive">
                                <form action="{{route('brand.update',$brand->id)}}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <table class="table user-table">
                                        <tbody>
                                            <tr>
                                                <label for="image">Hình Ảnh:</label>
                                                <input type="file" class="form-control" id="ful" name="image" value="{{$brand->image}}" style="padding-top: 3px">
                                                <tr><img id="imgPre" src="{{asset('public/images/img_brand/'.$brand->image)}}" alt="Không Có Ảnh" class="img-thumbnail" width="90"></ /></tr></br>
                                            </tr>
                                            <tr>
                                                <label for="name">Tên Thương Hiệu:</label>
                                            <input type="text" class="form-control" id="name" name="name" value="{{$brand->name}}">
                                            </tr>
                                            <tr>
                                                <label for="content">Mô Tả:</label>
                                                <textarea type="text" class="form-control" id='id_ckeditor' name="content">{{$brand->content}}</textarea>
                                            </tr>
                                            <tr>
                                                <label for="status">Trạng Thái:</label>
                                                <select type="text" class="form-control" id="status" name="status">
                                                    <option value="1" <?php if($brand->status==1){ echo 'selected'; } ?>>Còn Hàng</option>
                                                    <option value="0" <?php if($brand->status==0){ echo 'selected'; } ?>>Hết Hàng</option>
                                                </select>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <button type="submit" name="btnregister"class="btn btn-primary" style="background:#26c6da">Thực Hiện</button>
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script type="text/javascript">
                function readURL(input, idImg) {
                    if (input.files && input.files[0]) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $(idImg).attr('src', e.target.result);
                        }

                        reader.readAsDataURL(input.files[0]); // convert to base64 string
                    }
                }

                $("#ful").change(function () {
                    readURL(this, '#imgPre');
                });
            </script>
            @endsection

resources/views/admin/QLBrand/index.blade.php
@extends('layout_admin')
@section('admin_content')
<style>
.hidden{
    display: none;
}
</style>
    <div class="container-fluid">
                <div class="row" style="text-align: center;">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title" style="text-align:center">Thương Hiệu Sản Phẩm</h4>
                                <h6 class="card-subtitle">Thương Hiệu<code>.table</code></h6>
                                <a href="{{route('brand.create')}}" class="btn btn-primary" style="background:#26c6da">Thêm Thương Hiệu Sản Phẩm</a>
                                <div class="table-responsive">
                                    @if(Session::has('message'))
                                        <div class="alert alert-success">
                                            {{Session::get('message')}}
                                        </div>
                                    @endif
                                        <table class="table user-table">
                                            <thead>
                                                <tr>
                                                    <th class="border-top-0">#</th>
                                                    <th class="border-top-0">Hình Ảnh</th>
                                                    <th class="border-top-0">Tên Thương Hiệu</th>
                                                    <th class="border-top-0">Sản Phẩm</th>
                                                    <th class="border-top-0">Chỉnh Sửa</th>
                                                    <th class="border-top-0">Trạng Thái</th>
                                                    <th class="border-top-0">Xóa</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($brands ?? '' as $brand)
                                                <tr>
                                                    <td></td>
                                                    <td> <img src="{{asset('public/images/img_brand/'.$brand->image)}}" width="90"/></td>
                                                    <td>{{$brand->name}} </td>

                                                    <td><a href="{{route('brand.productlist',$brand->id)}}" class="btn btn-primary"><i class="fa fa-eye"></i></a></td>

                                                    <td><a href="{{route('brand.edit',$brand->id)}}" class="btn btn-primary"><i class="fa fa-edit"></i></a></td>

                                                    <td>
                                                        <?php
                                                        if($brand->status == 1)
                                                        { ?>
                                                            <a href="{{route('brand.unactive',$brand->id)}}" class="btn btn-warning"><i class="fa fa-unlock-alt"></i></a>
                                                        <?php }
                                                        else if($brand->status == 0)
                                                        { ?>
                                                            <a href="{{route('brand.active',$brand->id)}}" class="btn btn-warning" style="color: black"><i class="fa fa-lock"></i></a>
                                                        <?php } ?>
                                                    </td>

                                                    <td><a href="{{route('brand.delete',$brand->id)}}" class="btn btn-danger"><i class="fa fa-trash"></i></a></td>

                                                </tr>
                                                @endforeach
                                                <tr><td colspan="10">{{$brands->links()}}</td></tr>
                                            </tbody>
                                        </table>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    </div>
@endsection

resources/views/admin/QLBrand/productlist.blade.php
@extends('layout_admin')
@section('admin_content')

    <div class="container-fluid">
                <div class="row" style="text-align: center;">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title" style="text-align:center">Thương Hiệu Sản Phẩm</h4>
                                <h6 class="card-subtitle">Thương Hiệu
                                    @foreach($products ?? '' as $product)
                                        <?php foreach($brand as $br){
                                                            if($product->idbrand == $br->id)
                                                                echo $br->name;
                                        }?>
                                    @endforeach
                                <code>.table</code></h6>
                                <a href="{{route('product.create')}}" class="btn btn-primary" style="background:#26c6da">Thêm Sản Phẩm</a>
                                <div class="table-responsive">
                                    @if(Session::has('message'))
                                        <div class="alert alert-success">
                                            {{Session::get('message')}}
                                        </div>
                                    @endif
                                        <table class="table user-table">
                                            <thead>
                                                <tr>
                                                    <th class="border-top-0">#</th>
                                                    <th class="border-top-0">Hình Ảnh</th>
                                                    <th class="border-top-0">Tên Thương Hiệu</th>
                                                    <th class="border-top-0">Danh Mục</th>
                                                    <th class="border-top-0">Giá Bán</th>
                                                    <th class="border-top-0">Giảm Giá</th>
                                                    <th class="border-top-0">Chỉnh Sửa</th>
                                                    <th class="border-top-0">Trạng Thái</th>
                                                    <th class="border-top-0">Xóa</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($products ?? '' as $product)
                                                <tr>
                                                    <td></td>
                                                    <td> <img src="{{asset('public/images/img_product/'.$product->image)}}" width="90"/></td>
                                                    <td>{{$product->name}} </td>
                                                    <td>
                                                        <?php foreach($cat as $category){
                                                            if($product->idcat == $category->id)
                                                                echo $category->name;
                                                        }?>
                                                    </td>
                                                    <td>{{$product->price}} </td>
                                                    <td>{{$product->discount}} </td>

                                                    <td><a href="{{route('product.edit',$product->id)}}" class="btn btn-primary"><i class="fa fa-edit"></i></a></td>

                                                    <td>
                                                        <?php
                                                        if($product->status == 1)
                                                        { ?>
                                                            <a href="{{route('product.unactive',$product->id)}}" class="btn btn-warning"><i class="fa fa-unlock-alt"></i></a>
                                                        <?php }
                                                        else if($product->status == 0)
                                                        { ?>
                                                            <a href="{{route('product.active',$product->id)}}" class="btn btn-warning" style="color: black"><i class="fa fa-lock"></i></a>
                                                        <?php } ?>
                                                    </td>

                                                    <td><a href="{{route('product.delete',$product->id)}}" class="btn btn-danger"><i class="fa fa-trash"></i></a></td>

                                                </tr>
                                                @endforeach

                                            </tbody>
                                        </table>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    </div>
@endsection